import Head from "next/head";

import { Poppins } from "next/font/google";
import DefaultLayout from "@/components/layouts/DefaultLayout";
import Hero from "@/components/home/hero";

const poppins = Poppins({
  weight: "400",
  subsets: ["latin"],
});

const Home = () => {
  return (
    <>
      <Head>
        <title>Hey food</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={poppins.className} style={{ fontFamily: poppins.style.fontFamily }}>
        <Hero />
      </main>
    </>
  );
};

Home.getLayout = (page: any) => <DefaultLayout>{page}</DefaultLayout>;

export default Home;
